"""
This is a setup.py script generated by py2applet

Usage:
    python setup.py py2app
"""

from setuptools import setup
import sys
sys.setrecursionlimit(5000)

APP = ['buddy.py']
DATA_FILES = ['logo.png']
OPTIONS = {
    'includes': ['pymongo'],
    'argv_emulation': True,
    'packages': ['rumps', 'pymongo', 'dns'],
    'plist': {'CFBundleIconFile': 'logo.png'}
}

setup(
    app=APP,
    data_files=DATA_FILES,
    options={'py2app': OPTIONS},
    setup_requires=['py2app'],
)